from pydantic import BaseModel, Field
from typing import Optional, List


class NewsItem(BaseModel):
    """
    Represents a news headline or article about the company.
    """

    title: str = Field(..., description="Headline or title of the news item.")
    url: Optional[str] = Field(None, description="URL to the news article.")
    published_on: Optional[str] = Field(None, description="Publication date (YYYY-MM-DD).")
    summary: Optional[str] = Field(None, description="Short summary of the news item.")


class CompanyReport(BaseModel):
    """
    Structured research report about a company, generated by the Company Researcher agent.
    """

    # Identification and tracking fields
    job_title: Optional[str] = Field(
        None,
        description="Job title associated with this company research (for job-specific context).",
    )
    company_name: str = Field(..., description="Name of the company.")
    company_stage: Optional[str] = Field(
        None, description="Stage of the company, e.g., 'startup', 'mature', 'scale-up'."
    )
    overview: Optional[str] = Field(None, description="Brief overview of the company.")
    products: Optional[List[str]] = Field(None, description="List of main products or services.")
    recent_news: Optional[List[NewsItem]] = Field(
        None, description="Recent news items about the company."
    )
    culture_indicators: Optional[List[str]] = Field(
        None, description="Signals about company culture."
    )
    red_flags: Optional[List[str]] = Field(None, description="Potential concerns or red flags.")
    sources: Optional[List[str]] = Field(None, description="Sources used for the report.")
